'use client';
import { useSession } from 'next-auth/react';
import { useState, useEffect } from 'react';
import ProtectedRoute from '@/components/auth/ProtectedRoute';
import Link from 'next/link';
export const dynamic = 'force-dynamic';
interface EnquirySummary { _id: string; leadName: string; firstChoiceDestination: string; tripType: string; travelDate: string; numberOfGuests: number; numberOfNights: number; status: string; hasQuotes: boolean; quotesCount: number; createdAt: string; quotes?: Array<{ _id: string; status: string }>; }
interface QuoteSummary { _id: string; quoteReference: string; title: string; destination: string; leadName: string; hotelName: string; numberOfPeople: number; numberOfNights: number; arrivalDate: string; totalPrice: number; currency: string; status: string; emailSentAt: string; createdAt: string; }
interface BookingSummary { _id: string; quoteReference: string; title: string; destination: string; leadName: string; hotelName: string; numberOfPeople: number; numberOfNights: number; arrivalDate: string; totalPrice: number; currency: string; status: string; emailSentAt: string; }
interface PackageSummary { _id: string; name: string; destination: string; resort: string; currency: string; }
export default function AgentDashboardPage() {
  const { data: session } = useSession();
  const [enquiries, setEnquiries] = useState<EnquirySummary[]>([]);
  const [quotes, setQuotes] = useState<QuoteSummary[]>([]);
  const [bookings, setBookings] = useState<BookingSummary[]>([]);
  const [packages, setPackages] = useState<PackageSummary[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([ fetch('/api/agent/enquiries').then(r => r.ok ? r.json() : { data: [] }), fetch('/api/agent/quotes').then(r => r.ok ? r.json() : { data: [] }), fetch('/api/agent/bookings').then(r => r.ok ? r.json() : { data: [] }), fetch('/api/agent/super-packages').then(r => r.ok ? r.json() : { data: { packages: [] } }) ]).then(([e, q, b, p]) => { setEnquiries(e.data || []); setQuotes(q.data || []); setBookings(b.data || []); setPackages((p.data?.packages || []).slice(0, 6)); }).catch(console.error).finally(() => setLoading(false)); }, []);
  const sym = (c: string) => c === 'GBP' ? '£' : c === 'EUR' ? '€' : '$';
  const fmtDate = (d: string) => { try { return new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }); } catch { return '-'; } };
  const sentQuote = (enq: EnquirySummary) => enq.quotes?.find(q => q.status === 'sent' || q.status === 'updated');
  const hasSentQuote = (enq: EnquirySummary) => !!sentQuote(enq);
  const sBadge = (s: string, enq: EnquirySummary) => { if (hasSentQuote(enq)) return 'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-600/20'; if (enq.hasQuotes) return 'bg-purple-50 text-purple-700 ring-1 ring-purple-600/20'; return ({ 'new': 'bg-blue-50 text-blue-700 ring-1 ring-blue-600/20', 'in-progress': 'bg-amber-50 text-amber-700 ring-1 ring-amber-600/20', 'completed': 'bg-green-50 text-green-700 ring-1 ring-green-600/20' } as Record<string,string>)[s] || 'bg-gray-50 text-gray-700 ring-1 ring-gray-600/20'; };
  const sLabel = (s: string, enq: EnquirySummary) => { if (hasSentQuote(enq)) return 'Quote Ready'; if (enq.hasQuotes) return 'In Review'; return ({ 'new': 'Submitted', 'in-progress': 'In Progress', 'completed': 'Completed' } as Record<string,string>)[s] || s; };
  return (<ProtectedRoute><div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-orange-50/30">
    <div className="relative overflow-hidden bg-gradient-to-r from-gray-900 via-gray-800 to-gray-900"><div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"><div className="flex items-center justify-between"><div><p className="text-orange-400 text-sm font-medium tracking-wide uppercase">Agent Portal</p><h1 className="text-3xl font-bold text-white mt-1">Welcome back, {session?.user?.name || 'Agent'}</h1><p className="text-gray-400 mt-1">{session?.user?.companyName}{session?.user?.abtaPtsNumber ? ` · ${session.user.abtaPtsNumber}` : ''}</p></div><Link href="/enquiries" className="hidden sm:inline-flex items-center gap-2 bg-orange-500 hover:bg-orange-600 text-white px-5 py-2.5 rounded-lg font-medium transition-all hover:shadow-lg hover:shadow-orange-500/25"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>New Enquiry</Link></div></div></div>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-6"><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[{l:'Enquiries',v:enquiries.length,i:'💬'},{l:'Quotes Received',v:quotes.length,i:'📋'},{l:'Confirmed Bookings',v:bookings.length,i:'✅'},{l:'Awaiting Quote',v:enquiries.filter(e=>!hasSentQuote(e)&&!e.hasQuotes).length,i:'⏳'}].map((s,i)=>(<div key={i} className="bg-white rounded-xl shadow-sm border border-gray-100 px-4 py-4"><div className="flex items-center justify-between"><div><p className="text-2xl font-bold text-gray-900">{loading?'—':s.v}</p><p className="text-xs text-gray-500 mt-0.5">{s.l}</p></div><span className="text-xl">{s.i}</span></div></div>))}</div></div>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-6 pb-12">
      {/* My Enquiries */}
      <div className="bg-white rounded-xl border border-gray-100 shadow-sm mb-6 overflow-hidden"><div className="flex items-center justify-between px-6 py-4 border-b border-gray-100"><div className="flex items-center gap-2"><h2 className="text-lg font-semibold text-gray-900">My Enquiries</h2>{!loading&&<span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full">{enquiries.length}</span>}</div><div className="flex items-center gap-3"><Link href="/dashboard/enquiries" className="text-sm text-gray-500 hover:text-orange-600 font-medium">View all →</Link><Link href="/enquiries" className="text-sm bg-orange-500 hover:bg-orange-600 text-white px-3 py-1.5 rounded-lg font-medium transition-all">+ New</Link></div></div>
        {loading?(<div className="p-6 space-y-3">{[1,2,3].map(i=>(<div key={i} className="flex gap-3 animate-pulse"><div className="w-10 h-10 bg-gray-100 rounded-lg"/><div className="flex-1 space-y-2"><div className="h-4 bg-gray-100 rounded w-2/3"/><div className="h-3 bg-gray-100 rounded w-1/2"/></div></div>))}</div>):enquiries.length===0?(<div className="p-10 text-center"><p className="text-gray-400 text-sm">No enquiries yet</p><Link href="/enquiries" className="text-orange-600 text-sm font-medium mt-1 inline-block">Send your first enquiry →</Link></div>):(<div className="divide-y divide-gray-50">{enquiries.slice(0,8).map(enq=>{const sq=sentQuote(enq);const href=sq?`/dashboard/quotes/${sq._id}`:'/dashboard/enquiries';return(<Link key={enq._id} href={href} className="block px-6 py-3.5 hover:bg-gray-50/50 transition-colors"><div className="flex items-center justify-between"><div className="flex items-center gap-3 min-w-0"><div className="w-9 h-9 rounded-lg bg-gradient-to-br from-orange-100 to-orange-50 flex items-center justify-center flex-shrink-0"><span className="text-sm">{enq.tripType==='stag'?'🎩':enq.tripType==='hen'?'👑':'✈️'}</span></div><div className="min-w-0"><p className="font-medium text-gray-900 text-sm truncate">{enq.leadName}</p><p className="text-xs text-gray-500 truncate">{enq.firstChoiceDestination} · {enq.numberOfGuests} guests · {enq.numberOfNights}N · {fmtDate(enq.travelDate)}</p></div></div><div className="flex items-center gap-3 flex-shrink-0 ml-4"><span className="text-xs text-gray-400 hidden sm:inline">{fmtDate(enq.createdAt)}</span><span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${sBadge(enq.status,enq)}`}>{sLabel(enq.status,enq)}</span><svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7"/></svg></div></div></Link>);})}</div>)}</div>

      {/* My Quotes */}
      <div className="bg-white rounded-xl border border-gray-100 shadow-sm mb-6 overflow-hidden"><div className="flex items-center justify-between px-6 py-4 border-b border-gray-100"><div className="flex items-center gap-2"><h2 className="text-lg font-semibold text-gray-900">My Quotes</h2>{!loading&&<span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full">{quotes.length}</span>}</div></div>
        {loading?(<div className="p-6 space-y-3">{[1,2,3].map(i=>(<div key={i} className="flex gap-3 animate-pulse"><div className="w-10 h-10 bg-gray-100 rounded-lg"/><div className="flex-1 space-y-2"><div className="h-4 bg-gray-100 rounded w-2/3"/><div className="h-3 bg-gray-100 rounded w-1/2"/></div></div>))}</div>):quotes.length===0?(<div className="p-10 text-center"><p className="text-gray-400 text-sm">No quotes received yet</p><p className="text-gray-400 text-xs mt-1">Quotes will appear here once the team responds to your enquiries</p></div>):(<div className="divide-y divide-gray-50">{quotes.slice(0,8).map(q=>(<Link key={q._id} href={`/dashboard/quotes/${q._id}`} className="flex items-center justify-between px-6 py-3.5 hover:bg-gray-50/50 transition-colors"><div className="flex items-center gap-3 min-w-0"><div className="w-9 h-9 rounded-lg bg-gradient-to-br from-blue-100 to-blue-50 flex items-center justify-center flex-shrink-0"><span className="text-sm">📋</span></div><div className="min-w-0"><p className="font-medium text-gray-900 text-sm truncate">{q.title||q.leadName}</p><p className="text-xs text-gray-500 truncate">{q.destination} · {q.hotelName} · {q.numberOfPeople} guests · {q.numberOfNights}N</p></div></div><div className="flex items-center gap-4 flex-shrink-0 ml-4"><span className="text-xs text-gray-400 hidden sm:inline">{fmtDate(q.arrivalDate)}</span><span className="text-sm font-semibold text-gray-900">{sym(q.currency)}{q.totalPrice.toLocaleString()}</span><svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7"/></svg></div></Link>))}</div>)}</div>

      {/* My Bookings */}
      <div className="bg-white rounded-xl border border-gray-100 shadow-sm mb-6 overflow-hidden"><div className="flex items-center justify-between px-6 py-4 border-b border-gray-100"><div className="flex items-center gap-2"><h2 className="text-lg font-semibold text-gray-900">My Bookings</h2>{!loading&&<span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full">{bookings.length}</span>}</div><Link href="/dashboard/bookings" className="text-sm text-gray-500 hover:text-orange-600 font-medium">View all →</Link></div>
        {loading?(<div className="p-6 space-y-3">{[1,2,3].map(i=>(<div key={i} className="flex gap-3 animate-pulse"><div className="w-10 h-10 bg-gray-100 rounded-lg"/><div className="flex-1 space-y-2"><div className="h-4 bg-gray-100 rounded w-2/3"/><div className="h-3 bg-gray-100 rounded w-1/2"/></div></div>))}</div>):bookings.length===0?(<div className="p-10 text-center"><p className="text-gray-400 text-sm">No confirmed bookings yet</p><p className="text-gray-400 text-xs mt-1">Bookings appear here once a quote is accepted</p></div>):(<div className="divide-y divide-gray-50">{bookings.slice(0,8).map(b=>(<Link key={b._id} href={`/dashboard/bookings/${b._id}`} className="flex items-center justify-between px-6 py-3.5 hover:bg-gray-50/50 transition-colors"><div className="flex items-center gap-3 min-w-0"><div className={`w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0 ${b.status==='booked'?'bg-gradient-to-br from-emerald-100 to-emerald-50':'bg-gradient-to-br from-orange-100 to-orange-50'}`}><span className="text-sm">{b.status==='booked'?'✅':'⏳'}</span></div><div className="min-w-0"><p className="font-medium text-gray-900 text-sm truncate">{b.title||b.leadName}</p><p className="text-xs text-gray-500 truncate">{b.destination} · {b.hotelName} · {b.numberOfPeople} guests · {b.numberOfNights}N</p></div></div><div className="flex items-center gap-4 flex-shrink-0 ml-4"><span className="text-xs text-gray-400 hidden sm:inline">{fmtDate(b.arrivalDate)}</span><span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${b.status==='booked'?'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-600/20':'bg-orange-50 text-orange-700 ring-1 ring-orange-600/20'}`}>{b.status==='booked'?'Confirmed':'Awaiting Confirmation'}</span><span className="text-sm font-semibold text-gray-900">{sym(b.currency)}{b.totalPrice.toLocaleString()}</span><svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7"/></svg></div></Link>))}</div>)}</div>

      {/* Super Packages */}
      <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden"><div className="flex items-center justify-between px-6 py-4 border-b border-gray-100"><h2 className="text-lg font-semibold text-gray-900">Super Packages</h2><Link href="/dashboard/packages" className="text-sm text-orange-600 hover:text-orange-700 font-medium">Browse all packages →</Link></div>
        {loading?(<div className="p-6 grid grid-cols-2 sm:grid-cols-3 gap-3">{[1,2,3,4,5,6].map(i=><div key={i} className="h-20 bg-gray-100 rounded-lg animate-pulse"/>)}</div>):packages.length===0?(<div className="p-10 text-center"><p className="text-gray-400 text-sm">No packages available yet</p></div>):(<div className="p-4 grid grid-cols-2 sm:grid-cols-3 gap-3">{packages.map(pkg=>(<Link key={pkg._id} href="/dashboard/packages" className="group bg-gray-50 hover:bg-orange-50 rounded-lg p-4 transition-colors border border-transparent hover:border-orange-200"><p className="font-medium text-gray-900 text-sm group-hover:text-orange-700 truncate">{pkg.name.replace(/\s*20\d{2}\s*/g, ' ').trim()}</p><p className="text-xs text-gray-500 mt-0.5">{pkg.destination} · {pkg.resort}</p></Link>))}</div>)}</div>
    </div></div></ProtectedRoute>);
}
